export const Video_Data = [
    {
        "_id" : "video1",
        "videoTitle": "Falguni Pathak - Maine Payal Hai Chhankai",
        "videoURL" : "https://youtu.be/0tjVtYtZ384?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video1/Falguni_Thumbnail.gif",
        "videoDescription" : "Music video by Falguni Pathak performing Maine Payal Hai Chhankai. (C) 1999 Universal Music India Pvt. Ltd.",
        "videoCategory" : "Music",
        "channelId" : ["channel1"] ,
        "videoViews": "437,238,973 views",
        "videoUpload" : new Date("May 13, 2013"),
        
    },
    {
        "_id" : "video2",
        "videoTitle": "Ritviz - Thandi Hawa [Official Music Video]",
        "videoURL" : "https://youtu.be/0Hnw4nwaNCc?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video2/Ritviz_Thumbnail.gif",
        "videoDescription" : "Track Written, Composed, Produced and Performed by Ritviz.",
        "videoCategory" : "Music",
        "channelId" : ["channel2"],
        "videoViews": "6,951,515 views",
        "videoUpload" : new Date("May 5, 2020"),
        
    },
    {
        "_id" : "video3",
        "videoTitle": "Legend of Zelda: Echoes of Wisdom",
        "videoURL" : "https://youtu.be/hvNw6SNY8jA?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video3/Game1.gif",
        "videoDescription" : "better than barbuta",
        "videoCategory" : "Gaming",
        "channelId" : ["channel3"] ,
        "videoViews": "1,688,621 views",
        "videoUpload" : new Date("Septemer 30, 2024"),
        
    },
    {
        "_id" : "video4",
        "videoTitle": "Fall Guys - Tablet vs Console",
        "videoURL" : "https://youtu.be/d5erPXPj5-E?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video4/game2.gif",
        "videoDescription" : " #FallGuysMobile #EpicPartner Download Fall Guys on mobile now and play anywhere!",
        "videoCategory" : "Gaming",
        "channelId" : ["channel4"] ,
        "videoViews": "475,036 views",
        "videoUpload" : new Date("Septemer 7, 2024"),   
    },
    {
        "_id" : "video5",
        "videoTitle": "Sarojini Nagar | Stand-Up Comedy by Aakash Gupta",
        "videoURL" : "https://youtu.be/KBZfnt80s54?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video5/comedy1.gif",
        "videoDescription" : "#AakashGupta #SarojiniNagar #Standupcomedy",
        "videoCategory" : "Comedy",
        "channelId" : ["channel5"] ,
        "videoViews": "38,067,639 views",
        "videoUpload" : new Date("February 25, 2021"),
    },
    {
        "_id" : "video6",
        "videoTitle": "UPSC - Stand Up Comedy Ft. Anubhav Singh Bassi",
        "videoURL" : "https://youtu.be/IEfBBYmxtIo?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video6/comedy2.gif",
        "videoDescription" : "MY FIFTH STAND UP VIDEO IS HERE! DO WRITE YOUR UPSC PREPARATION EXPERIENCES IN COMMENTS.",
        "videoCategory" : "Comedy",
        "channelId" : ["channel6"] ,
        "videoViews": "62M views",
        "videoUpload" : new Date("November 25, 2023"),
    },
    {
        "_id" : "video7",
        "videoTitle": "Top 10 MUST-SEE Travel Destinations Around The World",
        "videoURL" : "https://youtu.be/tdgWEEOgdrU?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video7/Travel1.gif",
        "videoDescription" : " #BeautifulDestinations #Travel #Explore  Check out the World's Most Beautiful Places!",
        "videoCategory" : "Travel",
        "channelId" : ["channel7"] ,
        "videoViews": "15,509 views",
        "videoUpload" : new Date("January 20, 2024"),
    },
    {
        "_id" : "video8",
        "videoTitle": "25 Best Countries To Visit In 2024",
        "videoURL" : "https://youtu.be/HcdohhNq8Iw?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video8/Travel2.gif",
        "videoDescription" : "Travel Guide 2024 #travel #bestcountries",
        "videoCategory" : "Travel",
        "channelId" : ["channel8"],
        "videoViews": "1,181,903 views",
        "videoUpload" : new Date("December 10, 2023"),
    },
    {
        "_id" : "video9",
        "videoTitle": "The Crypto Expert: Bitcoin, Donald Trump, USA & Elon Musk",
        "videoURL" : "https://youtu.be/WJTB2jqzfB4?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video9/Podcasts1.gif",
        "videoDescription" : "Figuring Out With Raj Shamani",
        "videoCategory" : "Podcasts",
        "channelId" : ["channel9"] ,
        "videoViews": "164,792 views",
        "videoUpload" : new Date("November 19, 2024"),
    },
    {
        "_id" : "video10",
        "videoTitle": "The Best Podcast for Women of All Ages | Dr Anjali Kumar",
        "videoURL" : "https://youtu.be/vq2ZUSvWjJ0?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video10/Podcasts2.gif",
        "videoDescription" : "Figuring Out With Raj Shamani",
        "videoCategory" : "Podcasts",
        "channelId" : ["channel10"] ,
        "videoViews": "1.9M views",
        "videoUpload" : new Date("July 20, 2024"),
    },
    {
        "_id" : "video11",
        "videoTitle": "Pushpa 2 - The Rule Trailer (Hindi) | Allu Arjun",
        "videoURL" : "https://youtu.be/1kVK0MZlbI4?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video11/film1.gif",
        "videoDescription" : "Wait Is Over, The Ruler Has Come🔥! Presenting 'Pushpa 2 The Rule Trailer (Hindi)'.",
        "videoCategory" : "Films",
        "channelId" : ["channel11"],
        "videoViews": "74,086,898 views",
        "videoUpload" : new Date("November 17, 2024"),
    }, 
    {
        "_id" : "video12",
        "videoTitle": "Kanguva (Hindi) - Release Trailer | Suriya | Bobby Deol",
        "videoURL" : "https://youtu.be/ftcTEWWzhpk?feature=shared",
        "videoThumbnail": "/Image_Data/Videos/video11/film1.gif",
        "videoDescription" : "Studio Green K.E. Gnanavelraja in association with UV Creations Vamsi - Pramod presents Siva Directorial 'Kanguva'.",
        "videoCategory" : "Films",
        "channelId" : ["channel12"] ,
        "videoViews": "6,129,446 views",
        "videoUpload" : new Date("November 10, 2024"),
    }, 
    {
        "_id" : "video13",
        "videoTitle": "DEMO Video",
        "videoURL" : "https://youtu.be/NEuPTJeG1mM?feature=shared",
        "videoThumbnail": "/Demo Thumbnail.jpg",
        "videoDescription" : "Demo Videos created by Shruti Agrawal",
        "videoCategory" : "Music",
        "channelId" : ["channel1","channel2","channel3","channel4","channel5","channel6","channel7","channel8","channel9","channel10","channel11","channel12"] ,
        "videoViews": "1 view",
        "videoUpload" : new Date("November 10, 2024"),
    },
    {
        "_id" : "video14",
        "videoTitle": "DEMO Video",
        "videoURL" : "https://youtu.be/az6OZ0FC4ZI?feature=shared",
        "videoThumbnail": "/Demo Thumbnail.jpg",
        "videoDescription" : "Demo Videos created by Shruti Agrawal",
        "videoCategory" : "Podcasts",
        "channelId" : ["channel1","channel2","channel3","channel4","channel5","channel6","channel7","channel8","channel9","channel10","channel11","channel12"] ,
        "videoViews": "1 view",
        "videoUpload" : new Date("November 10, 2024"),
    },
    {
        "_id" : "video15",
        "videoTitle": "DEMO Video",
        "videoURL" : "https://youtu.be/n1Xa1s2UlIA?feature=shared",
        "videoThumbnail": "/Demo Thumbnail.jpg",
        "videoDescription" : "Demo Videos created by Shruti Agrawal",
        "videoCategory" : "Gaming",
        "channelId" : ["channel1","channel2","channel3","channel4","channel5","channel6","channel7","channel8","channel9","channel10","channel11","channel12"],
        "videoViews": "1 view",
        "videoUpload" : new Date("November 10, 2024"),
    },
    


];