export const Video_Data = [
    {
        "_id" : "video1",
        "videoTitle": "Falguni Pathak - Maine Payal Hai Chhankai",
        "videoURL" : "0tjVtYtZ384",
        "videoThumbnail": "/Image_Data/Videos/video1/Falguni_Thumbnail.gif",
        "videoDescription" : "Music video by Falguni Pathak performing Maine Payal Hai Chhankai. (C) 1999 Universal Music India Pvt. Ltd.",
        "videoCategory" : "Music",
        "channelId" : ["channel1"] ,
        "videoViews": "43 crore views",
        "videoLikes": 457,
        "videoDislikes":264,
        "videoUpload" : new Date("May 13, 2013"),
        
    },
    {
        "_id" : "video2",
        "videoTitle": "Ritviz - Thandi Hawa [Official Music Video]",
        "videoURL" : "0Hnw4nwaNCc",
        "videoThumbnail": "/Image_Data/Videos/video2/Ritviz_Thumbnail.gif",
        "videoDescription" : "Track Written, Composed, Produced and Performed by Ritviz.",
        "videoCategory" : "Music",
        "channelId" : ["channel2"],
        "videoViews": "69 lakh views",
        "videoLikes": 784,
        "videoDislikes":216,
        "videoUpload" : new Date("May 5, 2020"),
        
    },
    {
        "_id" : "video3",
        "videoTitle": "Legend of Zelda: Echoes of Wisdom",
        "videoURL" : "hvNw6SNY8jA",
        "videoThumbnail": "/Image_Data/Videos/video3/Game1.gif",
        "videoDescription" : "better than barbuta",
        "videoCategory" : "Gaming",
        "channelId" : ["channel3"] ,
        "videoViews": "16 lakh views",
        "videoLikes": 277,
        "videoDislikes":306,
        "videoUpload" : new Date("Septemer 30, 2024"),
        
    },
    {
        "_id" : "video4",
        "videoTitle": "Fall Guys - Tablet vs Console",
        "videoURL" : "d5erPXPj5-E",
        "videoThumbnail": "/Image_Data/Videos/video4/game2.gif",
        "videoDescription" : " #FallGuysMobile #EpicPartner Download Fall Guys on mobile now and play anywhere!",
        "videoCategory" : "Gaming",
        "channelId" : ["channel4"] ,
        "videoViews": "4.7 lakh views",
        "videoLikes": 699,
        "videoDislikes":86,
        "videoUpload" : new Date("Septemer 7, 2024"),   
    },
    {
        "_id" : "video5",
        "videoTitle": "Sarojini Nagar | Stand-Up Comedy by Aakash Gupta",
        "videoURL" : "KBZfnt80s54",
        "videoThumbnail": "/Image_Data/Videos/video5/comedy1.gif",
        "videoDescription" : "#AakashGupta #SarojiniNagar #Standupcomedy",
        "videoCategory" : "Comedy",
        "channelId" : ["channel5"] ,
        "videoViews": "3.8 crore views",
        "videoLikes": 656,
        "videoDislikes":298,
        "videoUpload" : new Date("February 25, 2021"),
    },
    {
        "_id" : "video6",
        "videoTitle": "UPSC - Stand Up Comedy Ft. Anubhav Singh Bassi",
        "videoURL" : "IEfBBYmxtIo",
        "videoThumbnail": "/Image_Data/Videos/video6/comedy2.gif",
        "videoDescription" : "MY FIFTH STAND UP VIDEO IS HERE! DO WRITE YOUR UPSC PREPARATION EXPERIENCES IN COMMENTS.",
        "videoCategory" : "Comedy",
        "channelId" : ["channel6"] ,
        "videoViews": "6.2 crore views",
        "videoLikes": 985,
        "videoDislikes":291,
        "videoUpload" : new Date("November 25, 2023"),
    },
    {
        "_id" : "video7",
        "videoTitle": "WONDERS OF INDIA | 15 Most Incredible Places You Must Visit",
        "videoURL" : "cOa97mBh8co",
        "videoThumbnail": "/Image_Data/Videos/video7/Travel1.gif",
        "videoDescription" : "Prepare to be amazed by the hidden wonders of India in this breathtaking video. From stunning landscapes to vibrant cultures, this is the most beautiful India video you'll ever see!",
        "videoCategory" : "Travel",
        "channelId" : ["channel7"] ,
        "videoViews": "1.3M views",
        "videoLikes": 949,
        "videoDislikes":289,
        "videoUpload" : new Date("Aug 2, 2024"),
    },
    {
        "_id" : "video8",
        "videoTitle": "25 Best Countries To Visit In 2024",
        "videoURL" : "HcdohhNq8Iw",
        "videoThumbnail": "/Image_Data/Videos/video8/Travel2.gif",
        "videoDescription" : "Travel Guide 2024 #travel #bestcountries",
        "videoCategory" : "Travel",
        "channelId" : ["channel8"],
        "videoViews": "1.1M views",
        "videoLikes": 479,
        "videoDislikes":580,
        "videoUpload" : new Date("December 10, 2023"),
    },
    {
        "_id" : "video9",
        "videoTitle": "The Crypto Expert: Bitcoin, Donald Trump, USA & Elon Musk",
        "videoURL" : "WJTB2jqzfB4",
        "videoThumbnail": "/Image_Data/Videos/video9/Podcasts1.gif",
        "videoDescription" : "Figuring Out With Raj Shamani",
        "videoCategory" : "Podcasts",
        "channelId" : ["channel9"] ,
        "videoViews": "1.9 lakh views",
        "videoLikes": 896,
        "videoDislikes":432,
        "videoUpload" : new Date("November 19, 2024"),
    },
    {
        "_id" : "video10",
        "videoTitle": "The Best Podcast for Women of All Ages | Dr Anjali Kumar",
        "videoURL" : "vq2ZUSvWjJ0",
        "videoThumbnail": "/Image_Data/Videos/video10/Podcasts2.gif",
        "videoDescription" : "Figuring Out With Raj Shamani",
        "videoCategory" : "Podcasts",
        "channelId" : ["channel10"] ,
        "videoViews": "19 lakh views",
        "videoLikes": 970,
        "videoDislikes":648,
        "videoUpload" : new Date("July 20, 2024"),
    },
    {
        "_id" : "video11",
        "videoTitle": "Pushpa 2 - The Rule Trailer (Hindi) | Allu Arjun",
        "videoURL" : "1kVK0MZlbI4",
        "videoThumbnail": "/Image_Data/Videos/video11/film1.gif",
        "videoDescription" : "Wait Is Over, The Ruler Has Come🔥! Presenting 'Pushpa 2 The Rule Trailer (Hindi)'.",
        "videoCategory" : "Films",
        "channelId" : ["channel11"],
        "videoViews": "7.6 crore views",
        "videoLikes": 674,
        "videoDislikes":210,
        "videoUpload" : new Date("November 17, 2024"),
    }, 
    {
        "_id" : "video12",
        "videoTitle": "Kanguva (Hindi) - Release Trailer | Suriya | Bobby Deol",
        "videoURL" : "ftcTEWWzhpk",
        "videoThumbnail": "/Image_Data/Videos/video12/film2.gif",
        "videoDescription" : "Studio Green K.E. Gnanavelraja in association with UV Creations Vamsi - Pramod presents Siva Directorial 'Kanguva'.",
        "videoCategory" : "Films",
        "channelId" : ["channel12"] ,
        "videoViews": "61 lakh views",
        "videoLikes": 784,
        "videoDislikes":523,
        "videoUpload" : new Date("November 10, 2024"),
    }, 
    {
        "_id" : "video13",
        "videoTitle": "DEMO Video",
        "videoURL" : "NEuPTJeG1mM",
        "videoThumbnail": "/Demo Thumbnail.jpg",
        "videoDescription" : "Demo Videos created by Shruti Agrawal",
        "videoCategory" : "Music",
        "channelId" : ["channel1","channel2","channel3","channel4","channel5","channel6","channel7","channel8","channel9","channel10","channel11","channel12"] ,
        "videoViews": "1 view",
        "videoLikes": 784,
        "videoDislikes":216,
        "videoUpload" : new Date("November 10, 2024"),
    },
    {
        "_id" : "video14",
        "videoTitle": "DEMO Video",
        "videoURL" : "az6OZ0FC4ZI",
        "videoThumbnail": "/Demo Thumbnail.jpg",
        "videoDescription" : "Demo Videos created by Shruti Agrawal",
        "videoCategory" : "Podcasts",
        "channelId" : ["channel3","channel2","channel1","channel4","channel5","channel6","channel7","channel8","channel9","channel10","channel11","channel12"] ,
        "videoViews": "1 view",
        "videoLikes": 784,
        "videoDislikes":216,
        "videoUpload" : new Date("November 10, 2024"),
    },
    {
        "_id" : "video15",
        "videoTitle": "DEMO Video",
        "videoURL" : "n1Xa1s2UlIA",
        "videoThumbnail": "/Demo Thumbnail.jpg",
        "videoDescription" : "Demo Videos created by Shruti Agrawal",
        "videoCategory" : "Gaming",
        "channelId" : ["channel9","channel2","channel3","channel4","channel5","channel6","channel7","channel8","channel9","channel10","channel11","channel12"],
        "videoViews": "1 view",
        "videoLikes": 784,
        "videoDislikes":216,
        "videoUpload" : new Date("November 10, 2024"),
    },
    


];